// <auto-generated />
namespace MohatechDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m121));
        
        string IMigrationMetadata.Id
        {
            get { return "201901041656150_m121"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
