// <auto-generated />
namespace MohatechDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m51 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m51));
        
        string IMigrationMetadata.Id
        {
            get { return "201901130017258_m51"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
